[package]
name = "pure-std"
version = "0.1.0"
authors = ["Laura Powles <laura@laurapowles.com>"]
edition = "2021"

license-file = "LICENSE"
description = "Pure alternatives to non-pure functions."
repository = "https://github.com/nebulaeandstars/pure-std"

[dependencies]
